### ISSUE TITLE
`Expr` instances are serialized as part of the graph

### ISSUE THREAD

**Issue by fjetter** [dask-contrib/dask-expr#323]
Running some profiling on the TCPH benchmarks, I noticed a significant portion of the main thread to be blocked by the calculation of `_meta` during the deserialization of `Expr` objects

![image](https://github.com/dask-contrib/dask-expr/assets/8629629/9d3a3bcc-4478-4f61-8dde-a93a0dfcfa03)

This screenshot indicates that the expr instance that is being (de-)serialized is the `Merge` expression.

Looking through the traces a bit more, I can also find references to a parquet layer which almost looks like it would fetch some data (but I hope this is false). It is definitely performing some pyarrow table conversion.

![image](https://github.com/dask-contrib/dask-expr/assets/8629629/f98b9e2a-c995-4b19-8090-0dc4f012ffd9)

speedscope file (a Worker)
[tls-10_0_32_152-45157.json.zip](https://github.com/dask-contrib/dask-expr/files/12847361/tls-10_0_32_152-45157.json.zip)

Just skimming the code, I saw stuff like this

https://github.com/dask-contrib/dask-expr/blob/52346744cf530ca86108553fb0427f552d91854e/dask_expr/_concat.py#L183

where a method of an expression is used to define a dask task. This inevitably requires us to serialize the instance itself which is something we should avoid. Ideally, the graph only includes global functions such that we can pickle by reference and not by value.

I don't know if there are other places where this pattern comes up.

related https://github.com/dask-contrib/dask-expr/pull/284

**Comment by rjzamora** [comment]
>Just skimming the code, I saw stuff like this ... `[[self._meta, key], 0, self.join, False, True]` ... where a method of an expression is used to define a dask task

In this case, `self.join` is a parameter (not a method). So, we definitely shouldn't need to serialize the expression.

**Comment by fjetter** [comment]
> In this case, self.join is a parameter (not a method). So, we definitely shouldn't need to serialize the expression.

Well, my mistake. Sorry. I haven't really tried to find out where this is happening, yet.

What's interesting is that for whatever objects this path is triggered, these objects have empty caches and according to my tests, `cached_property` is something that is preserved in pickle roundtrips

**Comment by rjzamora** [comment]
>Well, my mistake. Sorry. I haven't really tried to find out where this is happening, yet. I mixed it up with DataFrame.join which is a method

No problem - I just wanted to put your mind at ease about that particular detail. I'm glad to see you investigating serialization behavior in general.

>What's interesting is that for whatever objects this path is triggered, these objects have empty caches and according to my tests, cached_property is something that is preserved in pickle roundtrips

I suppose I don't really understand why expressions are bing pickled at all yet. Are you using a version of dask/distributed where expressions are shipped to the scheduler?

**Comment by rjzamora** [comment]
>The only way this makes sense if we accidentally pickle something by value.

Okay, I see. Thanks for clarifying! Then I agree that we shouldn't see any expression objects show up at all here (and should fix the fact that we do).

**Comment by fjetter** [comment]
So, the expression that ends up on the worker is a `RenameFrame` expression that includes a `Merge` expression as one of it's dependencies and the Merge is slow such that it pops up on the profile.

This object is deeply buried in a fused task.

**Comment by mrocklin** [comment]
Agreed that serializing task graphs shouldn't carry along expressions.  Probably some method is getting carried along somewhere.  If we had an `assert_eq` function of our own (maybe it's time for this) we could probably include something like this check in that function (we'd serialize any `__dask_graph__` that was present and ensure that it didn't include the bytes for an Expr class (if that's easy)).  

If we do serialize then I'd expect it to be cheap, see 

https://github.com/dask-contrib/dask-expr/blob/52346744cf530ca86108553fb0427f552d91854e/dask_expr/_expr.py#L138-L139

and 

https://github.com/dask-contrib/dask-expr/blob/52346744cf530ca86108553fb0427f552d91854e/dask_expr/tests/test_collection.py#L677-L693

It looks like the errant piece of code is coming out of the Parquet stuff, which does do more interesting caching than is common in other Expr subclasses.  It might makes sense to review that in particular.

**Comment by fjetter** [comment]
A simple albeit less elegant way to ensure this isn't serialized is also to just increase a counter whenever an object is serialized and assert that this is zero in subprocesses.

**Comment by fjetter** [comment]
Yes, I can also see a ParquetReader expression...

Digging in here a bit points to https://github.com/dask-contrib/dask-expr/blob/52346744cf530ca86108553fb0427f552d91854e/dask_expr/_groupby.py#L43

I'll have to run this again since I also had a `ddf.partitions[:2].sample(...)` in here but that one is definitely a problem. IIUC `Expr.operation` must not be a method but has to be a property since otherwise things start to break like this. If that's true, there are a couple of other offenders as well

**Comment by rjzamora** [comment]
Thanks for investigating that @fjetter - I do see how `GroupByChunk` can be a problem. I'll see if we can redesign a bit to avoid passing `chunk` as a parameter (and thus avoid the need for `operation` to be a method).

**Comment by fjetter** [comment]
I think the case we've seen has been addressed but I don't think we have tests for this, yet. I think we should have tests so I suggest to keep this open until we have them.

**Comment by rjzamora** [comment]
Yeah, I agree that we should keep this open until we have test coverage. Still not sure about the best way to do this.

**Comment by mrocklin** [comment]
For constraints that have to apply throughout the project my best
experience comes from using assert_eq like functions.  They're broadly used
throughout tests.  If we can make a check that is sufficiently cheap then
we can apply it to every Expr that comes through that function.  Such a
check might be serializing and then seeing if some reliably bad signal
comes through (such as any class that is part of the dask_expr module) or
having a counter on the reduce method (although I don't particularly like
adding state to expressions just for testing).  Another approach might be
to monkey patch an exception into the Expr reduce method during testing.
